version: "3"
services:
  web:
    image: fintech-app-auth-mservice:v1.1
    build: .
    command: node index.js
    ports:
      - "3000:3000"
    volumes:
      - ./usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
